### ISSUE TITLE
apiserver and asyncdelete-apiserver having the same selector

### ISSUE THREAD

**Issue by ockaro** [clearml/clearml-helm-charts#277]
### Describe the bug a clear and concise description of what the bug is.

Hi there,
when installing the helm chart of the clearml server a pod spawns called somewhat 'clearml-apiserver-asyncdelete-...'. The issue is that this pod has the same app selector as the apiserver pod. This results in very frequent 404s on the webapp because instead of the real api server the asyncdelete is called which sends 404s. When I delete the asyncdelete pod the issue with the 404s seems to be solved (but probably this pod is doing some important stuff so this can't be the solution :D).

### What's your helm version?

3.14.3

### What's your kubectl version?

1.25.2

### What's the chart version?

7.8.1

**Comment by valeriano-manassero** [comment]
Related PR and chart release should fix issue. Ty.
